name: Build ROS Packages

on:
  workflow_call:
    inputs:
      arch:
        required: false
        type: string
        default: amd64 # or arm64
      ubuntu_version:
        required: false
        type: string
        default: '22.04'
      ros_distro:
        required: false
        type: string
        default: 'humble'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-${{ inputs.ubuntu_version }}${{ inputs.arch == 'arm64' && '-arm' || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Extra Setup
        run: echo "DEB_DISTRO=$(lsb_release -sc)" >> $GITHUB_ENV
      - name: self-checkout
        run: |
              mkdir -p ./srcO/
              mv ./astra_* ./srcO/
              rm -rf ./src
      - uses: arendjan/ros-deb-builder-action@upmain # allows for failing builds
        env:
          ROS_DISTRO: ${{ inputs.ros_distro }}
        with:
          ROS_DISTRO: ${{ inputs.ros_distro }}
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          DEB_ARCH: ${{ inputs.arch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS_FILE: ./sources.repos
          SKIP_CHECKOUT: true
          PACKAGES_BRANCH: ros_mirte_${{ inputs.ros_distro }}_${{ env.DEB_DISTRO }}_${{ inputs.arch }}${{ github.ref == 'refs/heads/develop' && '_develop' || '' }}

        #   SBUILD_CONF: "$enable_network = 1;"
        #   Skip pushing to repo when not on main branch
          SKIP_PUSH: ${{ github.event_name == 'pull_request' || (github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop') }}
          UPLOAD_ARTIFACTS: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
          CONTINUE_ON_ERROR: true # allows for failing builds